name: Release builds

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Install dependencies
        run: go mod vendor

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --out-format=colored-line-number --modules-download-mode=vendor
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Run tests
        run: go test ./...

  goreleaser:
    name: Build with Goreleaser
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Vendor deps
        run: go mod vendor

      - name: Run Goreleaser (build only)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --snapshot --skip=publish --skip=sign --timeout=60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcp-cron-builds
          path: |
            dist/*.tar.gz
            dist/checksums.txt
